name: BMI-Calculator CI

# What one CI file can do:

# Run tests on 3 operating systems simultaneously
# Generate code coverage and upload to codecov
# Scan dependencies for security vulnerabilities
# Run performance benchmarks and compare to baseline
# Build binaries for Windows, Mac, Linux
# Create GitHub release with changelog
# Upload binaries as release assets
# Send Slack notification on success/failure
# Deploy to staging environment
# Run integration tests against live environment
# Auto-merge if all checks pass

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Linting
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
